name: Deploy Voilà Dashboard to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install voila
          pip install -r requirements.txt

      - name: Deploy with Voilà
        run: |
          voila --no-browser --port=8888
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
