name: Deploy Voilà Dashboard to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install voila
          pip install -r requirements.txt

      - name: Generate Voila app
        run: |
          voila notebook.ipynb --no-browser --port=8888
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Publish to GitHub Pages
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .
          mv *.html index.html
          git add .
          git commit -m "Publish Voilà app"
          git push origin gh-pages
